import { PrismaClient } from "@prisma/client";
import { faker } from "@faker-js/faker";

const prisma = new PrismaClient();

const NUM_AGENTS = 300;
const NUM_LISTINGS = 600;
const NUM_VIEWINGS = 1200;

const CITIES = [
  "New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
  "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose",
  "Austin", "Jacksonville", "Fort Worth", "Columbus", "San Francisco",
  "Charlotte", "Indianapolis", "Seattle", "Denver", "Washington",
  "Boston", "Nashville", "Detroit", "Portland", "Las Vegas"
];

const STATES = [
  "NY", "CA", "IL", "TX", "AZ",
  "PA", "TX", "CA", "TX", "CA",
  "TX", "FL", "TX", "OH", "CA",
  "NC", "IN", "WA", "CO", "DC",
  "MA", "TN", "MI", "OR", "NV"
];

const PROPERTY_TYPES = ["APARTMENT", "HOUSE", "CONDO", "TOWNHOUSE", "LAND"];
const LISTING_STATUSES = ["AVAILABLE", "PENDING", "SOLD", "RENTED"];
const VIEWING_STATUSES = ["SCHEDULED", "COMPLETED", "CANCELLED", "NO_SHOW"];

async function main() {
  console.log("🌱 Starting idempotent database seed with genuine cuid identifiers...");
  faker.seed(42);

  // 1. Seed Agents (Idempotent via unique licenseNumber, genuine cuid() generated by Prisma)
  console.log(`👤 Seeding ${NUM_AGENTS} agents...`);
  const agentCuids: string[] = [];

  for (let i = 1; i <= NUM_AGENTS; i++) {
    const cityIndex = i % CITIES.length;
    const city = CITIES[cityIndex];
    const name = faker.person.fullName();
    const email = `agent.${i}.${faker.internet.username().toLowerCase()}@momentumproperties.com`;
    const phone = faker.phone.number({ style: "national" });
    const agencyName = `${city} Real Estate Group`;
    const licenseNumber = `LIC-${city.substring(0, 3).toUpperCase()}-${String(10000 + i)}`;
    const status = i % 10 === 0 ? "INACTIVE" : "ACTIVE";

    // Upsert using the unique licenseNumber.
    // Notice: NO 'id' is passed in create! Prisma generates a genuine cuid() on create.
    const agent = await prisma.agent.upsert({
      where: { licenseNumber },
      update: {
        name,
        email,
        phone,
        agencyName,
        city,
        status,
      },
      create: {
        name,
        email,
        phone,
        agencyName,
        city,
        licenseNumber,
        status,
      },
    });

    // Store the genuine persisted cuid in our in-memory array for relationship mapping
    agentCuids.push(agent.id);
  }

  // 2. Seed Listings (Idempotent check-before-insert, genuine cuid() generated by Prisma)
  console.log(`🏠 Seeding ${NUM_LISTINGS} listings...`);
  // Load existing listings to make check-before-insert fast and idempotent in-memory
  const existingListings = await prisma.listing.findMany({
    select: { id: true, address: true, city: true },
  });
  const existingListingMap = new Map<string, string>(
    existingListings.map((l) => [`${l.address}::${l.city}`, l.id])
  );

  const listingCuids: string[] = [];

  for (let j = 1; j <= NUM_LISTINGS; j++) {
    const assignedAgentId = agentCuids[(j - 1) % agentCuids.length];
    const cityIndex = j % CITIES.length;
    const city = CITIES[cityIndex];
    const state = STATES[cityIndex];
    const propertyType = PROPERTY_TYPES[j % PROPERTY_TYPES.length];
    const status = LISTING_STATUSES[j % LISTING_STATUSES.length];
    const bedrooms = faker.number.int({ min: 1, max: 6 });
    const bathrooms = faker.number.float({ min: 1, max: 4, fractionDigits: 1 });
    const squareFeet = faker.number.int({ min: 500, max: 8000 });
    const price = faker.number.int({ min: 150000, max: 3500000 }) * 100;
    const title = `${faker.word.adjective()} ${bedrooms}BR ${propertyType.toLowerCase()} in ${city}`;
    const description = `Stunning ${propertyType.toLowerCase()} offering ${bedrooms} bedrooms and ${bathrooms} bathrooms in desirable ${city}. Features modern amenities, spacious layout with ${squareFeet} sq ft of living space, and excellent neighborhood convenience.`;
    const address = faker.location.streetAddress();
    const zipCode = faker.location.zipCode("#####");

    const lookupKey = `${address}::${city}`;
    let listingId = existingListingMap.get(lookupKey);

    if (!listingId) {
      // Check database if not in initial map
      const found = await prisma.listing.findFirst({
        where: { address, city },
        select: { id: true },
      });

      if (found) {
        listingId = found.id;
      } else {
        // Create new listing without specifying id - Prisma generates a genuine cuid()
        const created = await prisma.listing.create({
          data: {
            title,
            description,
            price,
            propertyType,
            status,
            bedrooms,
            bathrooms,
            squareFeet,
            address,
            city,
            state,
            zipCode,
            agentId: assignedAgentId,
          },
        });
        listingId = created.id;
      }
      existingListingMap.set(lookupKey, listingId);
    }

    listingCuids.push(listingId);
  }

  // 3. Seed Viewings (Idempotent check-before-insert, genuine cuid() generated by Prisma)
  console.log(`📅 Seeding ${NUM_VIEWINGS} viewings...`);
  const existingViewings = await prisma.viewing.findMany({
    select: { listingId: true, viewerEmail: true },
  });
  const existingViewingSet = new Set<string>(
    existingViewings.map((v) => `${v.listingId}::${v.viewerEmail}`)
  );

  for (let k = 1; k <= NUM_VIEWINGS; k++) {
    const assignedListingId = listingCuids[(k - 1) % listingCuids.length];
    const viewerName = faker.person.fullName();
    const viewerEmail = faker.internet.email({ firstName: viewerName.split(" ")[0] });
    const viewerPhone = faker.phone.number({ style: "national" });
    const scheduledAt = faker.date.between({
      from: new Date("2026-09-01T00:00:00Z"),
      to: new Date("2026-12-31T23:59:59Z"),
    });
    const status = VIEWING_STATUSES[k % VIEWING_STATUSES.length];
    const notes = k % 3 === 0 ? "Prospective buyer pre-approved for mortgage." : null;

    const viewingKey = `${assignedListingId}::${viewerEmail}`;

    if (!existingViewingSet.has(viewingKey)) {
      const found = await prisma.viewing.findFirst({
        where: { listingId: assignedListingId, viewerEmail },
        select: { id: true },
      });

      if (!found) {
        // Create new viewing without specifying id - Prisma generates a genuine cuid()
        await prisma.viewing.create({
          data: {
            listingId: assignedListingId,
            viewerName,
            viewerEmail,
            viewerPhone,
            scheduledAt,
            status,
            notes,
          },
        });
      }
      existingViewingSet.add(viewingKey);
    }
  }

  console.log("✅ Seed completed successfully with genuine cuid identifiers.");
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
